apiVersion: apps/v1
kind: Deployment
metadata:
  name: finn-deployment
  namespace: finn
  labels:
    app: finn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finn
  template:
    metadata:
      labels:
        app: finn
    spec:
      initContainers:
        - name: apply-migrations
          image: localhost:32000/finn:latest
          command: ["dotnet", "finn.dll", "--migrate"]
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: finn-env
          volumeMounts:
            - name: storage              
              mountPath: /app/data     

      containers:
        - name: app
          image: localhost:32000/finn:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: finn-env
          volumeMounts:
            - name: storage              
              mountPath: /app/data       

      volumes:                                # <-- Aqui no lugar certo
        - name: storage                  
          hostPath:
            path: /mnt/storage          
            type: Directory
