---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finn-deployment
  namespace: finn
  labels:
    app: finn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finn
  template:
    metadata:
      labels:
        app: finn
    spec:
      containers:
        - name: app
          image: localhost:32000/finn:v0.1.3
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
          
---

apiVersion: v1
kind: Service
metadata:
  namespace: finn
  name: finn-svc
  labels:
    finn.service: finn
spec:
  type: NodePort
  selector:
    app: finn
  ports:
    - name: finn-api
      port: 5000
      targetPort: 5000
      nodePort: 30001