apiVersion: apps/v1
kind: Deployment
metadata:
  name: finn-deployment
  namespace: default
  labels:
    app: finn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finn
  template:
    metadata:
      labels:
        app: finn
    spec:
      containers:
        - name: app
          image: localhost:32000/finn:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
